### ISSUE TITLE
Test builds are failing (except on macOS)

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/setup-julia#135]
Recently the nightly builds have started to fail, e.g. https://github.com/julia-actions/setup-julia/actions/runs/4255325653/jobs/7402784582

```
> ncc build

ncc: Version 0.22.3
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:58216)
    at module.exports (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:60642)
    at runCmd (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:47355)
    at 819 (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:44227)
    at __webpack_require__ (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:169)
    at startup (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:339)
    at module.exports.8 (/home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:371)
    at /home/runner/work/setup-julia/setup-julia/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:381 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

@sunoru do you happen to have any idea what causes this?

**Comment by SaschaMann** [comment]
It's all test builds, not just nightly

**Comment by sunoru** [comment]
https://stackoverflow.com/a/69699772/2824258

We can just deprecate `@zeit/ncc` in favor of `@vercel/ncc`.
